### ISSUE TITLE
Update the underdevelopment page.

### ISSUE THREAD

**Issue by pankajan05** [Earth-Restoration/UnderDevelopment#1]
- Add ER logo and link to ER home page.
- Update the color theme to the green color
- Add the footer section as developed by Elzian Agro and link to elzian agro home page.

Logo : https://drive.google.com/drive/folders/1gSXfsq-ve-xmAKU8y6JjuPy5FAc_kRiQ?usp=sharing

**Comment by AshenIR** [comment]
Fix the mention issues
